version: '3.9'
services:
  api:
    build: 
      context: .
      target: dev
    restart: always
    volumes:
      - ./:/srv/
      - /srv/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./.env

  mysql:
    image: mysql
    restart: always
    volumes:
      - ./.cache/data/:/var/lib/mysql
    environment:
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
