version: '3.9'
services:
  api:
    build:
      target: dev
    restart: always
    volumes:
      - ./:/srv/
      - /srv/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./.env
  mysql:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password 
    restart: always
    volumes:
      - ./data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
